### ISSUE TITLE
quinn-proto needs a new version, because rustls-platform-verifier@=0.4.0 does not compile with stable rustc 1.85.0

### ISSUE THREAD

**Issue by getong** [quinn-rs/quinn#2174]
Currently, quinn-proto v0.11.9 , which ships with rustls-platform-verifier@=0.4.0

But the latest main branch update rustls-platform-verifier to 0.5, which compile with stable version rustc 1.85.0

solana-client v2.2.3 -> solana-udp-client v2.2.3 -> solana-streamer v2.2.3  -> quinn-proto v0.11.9

The compile error log can see https://github.com/subquery/network-indexer-services/actions/runs/13914840466/job/38935914357

```
#14 151.2    Compiling solana-rayon-threadlimit v2.2.3
#14 151.3    Compiling bitvec v1.0.1
#14 151.7    Compiling dlopen2 v0.5.0
#14 151.9    Compiling ark-serialize v0.4.2
#14 152.1    Compiling rustls-platform-verifier v0.4.0
#14 152.2 error[E0277]: the trait bound `webpki::Error: std::error::Error` is not satisfied
#14 152.2    --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-platform-verifier-0.4.0/src/verification/others.rs:234:40
#14 152.2     |
#14 152.2 234 |             other_err.0.downcast_ref::<webpki::Error>()
#14 152.2     |                         ------------   ^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `webpki::Error`
#14 152.2     |                         |
#14 152.2     |                         required by a bound introduced by this call
#14 152.2     |
#14 152.2 note: required by a bound in `<(dyn std::error::Error + Send + Sync + 'static)>::downcast_ref`
#14 152.2    --> /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/error.rs:271:5
#14 152.2 
#14 152.2 For more information about this error, try `rustc --explain E0277`.
#14 152.3 error: could not compile `rustls-platform-verifier` (lib) due to 1 previous error
```

**Comment by getong** [comment]
https://github.com/MystenLabs/sui/issues/21509#issuecomment-2731635204

```
rustls-webpki = "0.102"
```

**Comment by djc** [comment]
Published [quinn 0.11.7 and quinn-proto 0.11.10](https://github.com/quinn-rs/quinn/releases/tag/quinn-proto-0.11.10).

**Comment by getong** [comment]
thanks, I make https://github.com/anza-xyz/agave/pull/5347
