### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [quinn-rs/quinn#1142]
Regressed by b681c654124d (usize) and 1bc75aa01486 (in_pktinfo)

```rust
$ pkg install rust
$ rustc -vV
rustc 1.52.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-freebsd
release: 1.52.1
LLVM version: 12.0.0

$ cargo build
[...]
error[E0422]: cannot find struct, variant or union type `in_pktinfo` in crate `libc`
   --> quinn/src/platform/unix.rs:387:41
    |
387 |                       let pktinfo = libc::in_pktinfo {
    |                                           ^^^^^^^^^^ help: a struct with a similar name exists: `in6_pktinfo`
    |
   ::: ../libc-0.2.97/src/unix/bsd/freebsdlike/mod.rs:82:1
    |
82  | / s! {
83  | |     pub struct in_addr {
84  | |         pub s_addr: ::in_addr_t,
85  | |     }
...   |
346 | |     }
347 | | }
    | |_- similarly named struct `in6_pktinfo` defined here

error[E0425]: cannot find value `IP_PKTINFO` in crate `libc`
   --> quinn/src/platform/unix.rs:394:58
    |
394 |                     encoder.push(libc::IPPROTO_IP, libc::IP_PKTINFO, pktinfo);
    |                                                          ^^^^^^^^^^ help: a constant with a similar name exists: `IPV6_PKTINFO`
    |
   ::: ../libc-0.2.97/src/unix/bsd/freebsdlike/mod.rs:919:1
    |
919 | pub const IPV6_PKTINFO: ::c_int = 46;
    | ------------------------------------- similarly named constant `IPV6_PKTINFO` defined here

error[E0531]: cannot find unit struct, unit variant or constant `IP_PKTINFO` in crate `libc`
   --> quinn/src/platform/unix.rs:454:38
    |
454 |             (libc::IPPROTO_IP, libc::IP_PKTINFO) => unsafe {
    |                                      ^^^^^^^^^^ help: a constant with a similar name exists: `IPV6_PKTINFO`
    |
   ::: ../libc-0.2.97/src/unix/bsd/freebsdlike/mod.rs:919:1
    |
919 | pub const IPV6_PKTINFO: ::c_int = 46;
    | ------------------------------------- similarly named constant `IPV6_PKTINFO` defined here

error[E0412]: cannot find type `in_pktinfo` in crate `libc`
   --> quinn/src/platform/unix.rs:455:52
    |
455 |                   let pktinfo = cmsg::decode::<libc::in_pktinfo>(cmsg);
    |                                                      ^^^^^^^^^^ help: a struct with a similar name exists: `in6_pktinfo`
    |
   ::: ../libc-0.2.97/src/unix/bsd/freebsdlike/mod.rs:82:1
    |
82  | / s! {
83  | |     pub struct in_addr {
84  | |         pub s_addr: ::in_addr_t,
85  | |     }
...   |
346 | |     }
347 | | }
    | |_- similarly named struct `in6_pktinfo` defined here

error[E0308]: mismatched types
   --> quinn/src/platform/unix.rs:287:17
    |
287 |                 bufs.len().min(BATCH_SIZE) as libc::c_uint,
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `u32`
    |
help: you can convert a `u32` to a `usize` and panic if the converted value doesn't fit
    |
287 |                 (bufs.len().min(BATCH_SIZE) as libc::c_uint).try_into().unwrap(),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0308, E0412, E0422, E0425, E0531.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `quinn`
```

**Comment by djc** [comment]
For the usize we should probably change not(macos) to linux? For the pktinfo types, do those exist on BSDs? Maybe add them in libc upstream?

**Comment by jbeich** [comment]
> For the pktinfo types, do those exist on BSDs? Maybe add them in libc upstream?

`IP_PKTINFO` exists on [NetBSD](https://github.com/netbsd/src/commit/94b7bfa100ff90e4cc35ff2ddceb2192a6344b7f) but not DragonFly, FreeBSD, OpenBSD. CC @asomers

**Comment by asomers** [comment]
That's right, FreeBSD doesn't implement IP_PKTINFO.  The closest thing it has, I think, is `getsockname`.  You should just not compile those sections on FreeBSD.

**Comment by Matthias247** [comment]
Keep in mind this is more than just "doesn't compile", and fixing the compilation won't fix the underlying problem.
Without `IP_PKTINFO` you won't be able to bind the server to a wildcard IPv4 address, since outgoing packets won't find the right way. 

So you have to choose between binding to a specific listener, using IPv6 or not using server support.

**Comment by Ralith** [comment]
> outgoing packets won't find the right way

This is only a problem if the machine actually has multiple addresses on the same subnet, right?

**Comment by DemiMarie** [comment]
@Matthias247 @Ralith IP_RECVDSTADDR and IP_SENDSRCADDR might help.

**Comment by Ralith** [comment]
Those do sound relevant! I don't think we have any capacity to test on BSD ourselves, however, so in any case we need someone with a suitable environment to contribute.

**Comment by Error996** [comment]
i can test,anytime unless sleep

**Comment by Ralith** [comment]
Nice! If you're interested in implementing this, we'd be happy to review a PR.

**Comment by xpader** [comment]
Any updates? I can help to test too.

**Comment by djc** [comment]
There are no updates as far as I know -- someone still needs to make the required code changes.

**Comment by InfRandomness** [comment]
I'd be willing to put some work into this; we (the veloren project) use quinn and quinn-udp for our game
fixing this issue would not only make the game one step closer to running on freebsd but also help a whole lot of other people

**Comment by Ralith** [comment]
Thanks for your interest! Feel free to reach out on gitter/matrix if you have any questions. Should be limited to mostly boring changes to quinn-udp/src/unix.rs.

**Comment by p-kraszewski** [comment]
What fascinates me the most, the troubleigiving fragment of the code is guarded by `if cfg!(target_os = "linux") { }` and should not be interpreted on FreeBSD in the first place...

**Comment by Ralith** [comment]
That expands to `if false { ... }` on FreeBSD, in which case the `...` must still be well-formed code. Does suggest a simple fix, though, if someone's motivated to try and validate it!
