### ISSUE TITLE
Using `rustls` v22 and greater with quinn

### ISSUE THREAD

**Issue by ReeceHumphreys** [quinn-rs/quinn#1795]
The documentation shows an example of how to integrate `rustls` with quinn:

```rust
    let crypto = rustls::ClientConfig::builder()
        .with_safe_defaults()
        .with_custom_certificate_verifier(SkipServerVerification::new())
        .with_no_client_auth();

    ClientConfig::new(Arc::new(crypto))
```

However, the API for `rustls` has slightly changed and this example no longer seems to work:

```rust
        let crypto = rustls::ClientConfig::builder()
            .with_root_certificates(roots)
            .with_no_client_auth();


        quinn::ClientConfig::new(Arc::new(crypto));
```

**Error:**

```shell
error[E0277]: the trait bound `rustls::ClientConfig: quinn::crypto::ClientConfig` is not satisfied
  --> src/icerpc_connection.rs:38:54
   |
38 |         let client_config = quinn::ClientConfig::new(Arc::new(crypto));
   |                                                      ^^^^^^^^^^^^^^^^ the trait `quinn::crypto::ClientConfig` is not implemented for `rustls::ClientConfig`
   |
   = help: the trait `quinn::crypto::ClientConfig` is implemented for `rustls::client::client_conn::ClientConfig`
   = note: required for the cast from `Arc<rustls::ClientConfig>` to `Arc<(dyn quinn::crypto::ClientConfig + 'static)>`

```

Any help with resolving this would be greatly appreciated!

**Comment by ReeceHumphreys** [comment]
I suspect https://github.com/quinn-rs/quinn/pull/1715 would resolve my issue but I am looking for a workaround in the meantime if possible!

**Comment by djc** [comment]
Look at the examples from any Git tags?

**Comment by djc** [comment]
In general Quinn does not and will not support rustls 0.22. It will support rustls 0.23 after #1715 lands. If you want to get something working today, you can either use released Quinn with rustls 0.21 or try to make a git dependency work with rustls 0.23 (but I will be force-pushing to the #1715 branch, so it's not a very stable target right now).

**Comment by ReeceHumphreys** [comment]
Thanks for there guidance!

**Comment by jonatanzeidler** [comment]
To me looks a lot like #1600 and #300.
